name: Build and deploy ASP.Net Core app to Azure Web App - store-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release Store/Store.API/Store.API.csproj

      - name: dotnet publish
        run: dotnet publish Store/Store.API/Store.API.csproj -c Release -o ${{ github.workspace }}/myapp
      
      - name: Zip published files
        run: |
          Compress-Archive -Path ${{ github.workspace }}/myapp/* -DestinationPath ${{ github.workspace }}/myapp.zip
        shell: pwsh
          
      - name: List published files
        run: ls -R ${{ github.workspace }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'store-api'
          slot-name: 'Production'
          package: ${{ github.workspace }}/myapp.zip

      - name: Apply EF Core Migrations
        run: |
          dotnet ef database update --no-build --project Store/Store.API/Store.API.csproj
        env:
          ASPNETCORE_ENVIRONMENT: Production
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
